Fix "Tapping caskroom/cask has failed!" error
Fix problem encountered when running script/setup with latest version of
Homebrew:

```
$ script/setup
brew bundle can't satisfy your Brewfile's dependencies.
Satisfy missing dependencies with `brew bundle install`.
Error: caskroom/cask was moved. Tap homebrew/cask-cask instead.
Tapping caskroom/cask has failed!
```

/xref https://github.com/jasonrudolph/ControlEscape.spoon/pull/6